---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: app
          image: docker.fast.ar/sample:latest
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: test
spec:
  selector:
    app: sample
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample
  namespace: test
spec:
  secretName: sample-fast-ar-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - sample.fast.ar
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sample-registry-ingress-secure
  namespace: test
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`sample.fast.ar`)
    kind: Rule
    services:
    - name: sample-service
      port: 8080
  tls:
    secretName: sample-fast-ar-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sample-registry-ingress
  namespace: test
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`sample.fast.ar`)
    kind: Rule
    services:
    - name: sample-service
      port: 8080
    middlewares:
    - name: https-redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: test
spec:
  redirectScheme:
    scheme: https
    permanent: true