---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: app
          image: docker.fast.ar/sample:latest
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: test
spec:
  selector:
    app: sample
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---