apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: kevin-vargas
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: app
          image: registry.cloud.okteto.net/kevin-vargas/sample:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: ":8080"
      imagePullSecrets:
        - name: okteto-regcred
---
apiVersion: v1
kind: Service
metadata:
  name:  sample-service
  namespace: kevin-vargas
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app:  sample
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    dev.okteto.com/generate-host: "true"
  name: sample-ingress
  namespace: kevin-vargas
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: sample
          servicePort: 8080
        path: /