name: pr check

on:
  pull_request:
    branches: [main]

jobs:
  gitflow:
    runs-on: ubuntu-20.04
    steps:
    - name: Set environment variables
      run: |
        echo "GIT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
    - name: Branch Name Check
      run: |
        ALLOWED="((feature|fix)\/[A-Z0-9a-z-]+)$"
        echo "branch is $GIT_BRANCH"
        if ! [[ "$GIT_BRANCH" =~ $ALLOWED ]]
        then
            echo "Wrong branch name"
            exit 1
        fi
        echo "Successful branch name check"
  coverage:
    runs-on: ubuntu-20.04
    needs: gitflow
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Coverage Report
      env:
        TEST_COVERAGE_THRESHOLD: 70
      run: |
        make coverage
        TOTAL=$(go tool cover -func=./backend/coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
        if (( $(echo "$TOTAL <= $TEST_COVERAGE_THRESHOLD" | bc -l) ))
        then
            echo "Current test coverage is below threshold. ${TOTAL}% < ${TEST_COVERAGE_THRESHOLD}%"
            exit 1
        fi
        echo "Successful coverage test"